services:
  auth-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  orders-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - orders-db-data:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  registry-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: registry
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - registry-db-data:/var/lib/postgresql/data
    ports:
      - '5437:5432'

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: always

volumes:
  auth-db-data:
  orders-db-data:
  registry-db-data:
  rabbitmq-data:
  redis-data:
